### ISSUE TITLE
Building Javacpp-presets on Windows 64bit: short guide

### ISSUE THREAD

**Issue by maximumspatium** [bytedeco/javacpp-presets#44]
Hello guys and girlz,

I've just managed to compile Javacpp-presets from source on Windows 7. This was a major hackage so I've decided to write this short guide in order to save you a couple of days messing around with Windows and prevent some big frustrations. :disappointed_relieved: 

**1. First of all, you'll need to install the following dependencies:**

**MSYS2:** http://msys2.github.io
*WARNING: please don't use MSYS from mingw.org because it's hopelessly obsolete and doesn't support 64bit targets!*

Download the appropriate package for your system architecture, run it and choose the following installation path:
```
C:\msys64
```
After installation please follow the instructions given on the site in order to initialize the package manager ```pacman``` and update system packages.

Then you'll need to install **tar** because it's requiered but isn't installed by default. Open the MSYS2 console from "Start" menu and type the folowing command:
```pacman -S tar```

**Windows Platform SDK:** http://www.microsoft.com/en-us/download/details.aspx?id=8279
*This one is for Windows 7. You may actually need another SDK if you're running another Windows version.*

**MingW-w64 compiler toolset:** http://mingw-w64.yaxm.org/doku.php/download
Download the installer from the above-mentioned site, run it, choose the installation path to be
```
C:\mingw64
```
and architecture = x86_64, threading model = win32, exception handling = SEH and build revision = 2.

**7zip decompression package** from here: http://www.7-zip.org/download.html
Please ensure that 7zip executable has been properly installed to
```
C:\Program Files\7-Zip\7z.exe
```

**Java 7 JDK:** http://www.oracle.com/technetwork/java/javase/downloads/index.html
**Please ensure that the downloaded JDK does correspond to your system architecture!**

Install **Maven** from https://maven.apache.org/download.cgi and set it up as described here: https://maven.apache.org/guides/getting-started/windows-prerequisites.html
Make sure that the ```mvn --version``` command issued from the command line prints meaningful Maven version.

**Now you'll need to add the following code to your Windows PATH:**
```
C:\msys64\usr\bin;C:\mingw64\mingw64\bin
```
Now fire up the __Windows SDK Command Prompt (sic!)__ and issue the following commands:
```
bash --version
g++ --version
```
If it works you're ready to proceed with the compilation.

**You'll need to compile and install the parent project - Javacpp - first.**

**Then proceed with compilation of Javacpp-presets:**
1) download or clone the latest source code and extract it to said ```javacpp-presets```
2) open the __Windows SDK Command Prompt (sic!)__ and issue the following command:
```
cd javacpp-presets
bash cppbuild.sh -platform windows-x86_64 install leptonica tesseract or whatever else
```
If you'll forget to launch Windows SDK Command Prompt you'll get ```TARGET_CPU: unbound variable``` error!

If everything went well during the previous step, build the Java part as follows:
```
mvn install --project .,leptonica,tesseract
```
Don't forget the dot in the beginning of the projects list!

Have fun and keep on smiling! :smile: 
Max

**Comment by saudet** [comment]
Wow, this is great! Thanks a lot! It would make a great wiki page:
https://github.com/bytedeco/javacpp-presets/wiki
Could you put up one up with that content? You should have permission.Thanks in advance!

**Comment by ideastorm** [comment]
Thanks so much, maximumspatium (and saudet) for this!  I still ran into some issues, so I'm going to document what I went through to get this working on Windows 8.1.

http://mingw-w64.yaxm.org/doku.php/download lists three different installers.  I selected the "Mingw-builds project - native toolchains using trunk" installer.

The Windows 8.1 SDK does not install a "Windows SDK Command Prompt", so you'll need to either add an environment variable for TARGET_CPU, or set it manually before calling the build script:
```
set TARGET_CPU=x64
cd javacpp-presets
bash cppbuild.sh -platform windows-x86_64 install leptonica tesseract or whatever else
```

You need to include -platform windows-x64_64, or your build won't work and you'll get lots of messages like this:
>Error: Platform "msys_nt-6.3-x86_64" is not supported

Various projects will require additional tools to build properly - in particular, you'll need unzip and patch.  You can install these when you install tar.
```
pacman -S tar unzip patch
```

If you get the following error (line number may vary):
```
cppbuild.sh: line 230: lib: command not found
```
It's because the version of the Windows SDK you've got does not include a complete build environment - meaning you don't have the 'lib' tool (worst name ever - it's impossible to google).  The lack of a build environment is also why you have to specify TARGET_CPU manually.

One way to fix this is to download Visual Studio. :anguished:  You can download the community edition (~9GB installed) for free here: 
https://www.visualstudio.com/en-us/products/free-developer-offers-vs.aspx
I launched Visual Studio after installing and before trying again with the build script - Not sure if that's strictly necessary or not.  

After installing, you will need to add `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin` (actual path will vary if you've got a different version or installed to a different location) to your path.  If your version of Visual Studio has a developer command line, use that instead.  If not, I found that the community edition has a bat file that will set up your environment for you: `%VisualStudioInstallPath%\Common7\Tools\VsDevCmd.bat`

It appears libfreenect (kinect support) and possibly other projects require cmake.  I don't need kinect support, so I didn't look into where to find cmake.

Finally, before you can do the maven install, you'll need to have the JavaCPP library installed as well.  May be obvious, but I didn't realize it until Maven told me I was missing dependencies.

**Comment by maximumspatium** [comment]
Hi ideastorm,

thank you for your report - it looks like every Windows version has its own pecularities! Moreover, different projects inside javacpp-presets could require additional software like ```patch``` and ```unzip```. Thank you for pointing that out!
 
I'm not sure if I can help you to get a working build because I don't own any copy of Windows 8.1 (I'm kind of a Macintosh/Linux dude and usually try to avoid Windows whenever possible). Has the C++ part been completed without errors? I'd give a try if you would post the error log during the C++ build to a paste service like pastebin and drop the link to maximumspatium at googlemail dot com.

It looks suspicious to me that your build requires lib.exe. This tool is usually required for migrating shared libraries between GCC and MSVC. I cannot remember my Windows build has ever required it (and I didn't need to install Visual Studio to get lib.exe). Is it something JavaCPP does under the hood? Perhaps Samuel could shed some light on this issue.

I'll add an appropriate wiki page soon as suggested by Samuel...

Best regards
Max

**Comment by saudet** [comment]
Yeah, Windows isn't exactly developer-friendly. Here are the details of my current installation, that I've been using for a while now, but it still works and I don't use Windows for anything else right now:
- Windows XP Professional x64 Edition
- [Windows SDK 7.1](http://www.microsoft.com/en-us/download/details.aspx?id=8279)
- [msys+7za+wget+svn+git+mercurial+cvs-rev13.7z](http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/)
- [mingw-w64-install.exe](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download) (for both 32-bit and 64-bit versions with options that match with `mingw32` and `mingw64` packages from Fedora)
- [7-Zip 9.20 64-bit x64](http://www.7-zip.org/)

And we have to start MSYS inside a "Windows SDK Command Prompt" to get all the environment variables, as well as `mingw-w64.bat` to get GCC in the path.

I hope this will help you guys create a nice wiki page! Thanks for your interest.

**Comment by maximumspatium** [comment]
Hi Samuel,

do you have any clue why the FFMpeg-preset does require lib.exe?
Best regards
Max

**Comment by saudet** [comment]
@maximumspatium It's because of this here:
http://ffmpeg.org/platform.html#Linking-to-FFmpeg-with-Microsoft-Visual-C_002b_002b
I decided to use MSVC because CUDA doesn't work with GCC on Windows, but now that we need to use GCC for C++ with Tesseract anyway, we could switch to GCC for FFmpeg as well, and we would not need that hack.

**Comment by maximumspatium** [comment]
@saudet
Done, see here: https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows
Please feel free to correct possible mistakes.

**Comment by saudet** [comment]
Great! Looks awesome :+1:  Thank you!

**Comment by saudet** [comment]
FYI, I've updated my build system, patched a couple of things that needed change (https://github.com/bytedeco/javacpp-presets/commit/0b49621063ad0d201fb52f15a479448327ba5328) and figured out a slightly simpler procedure for Windows:

0. Install the JDK and Maven 3  https://maven.apache.org/
1. Install 7-Zip  http://www.7-zip.org/
2. Install Visual Studio Community 2013  https://www.visualstudio.com/
3. Install MSYS2  https://msys2.github.io/
4. Under MSYS2, run `pacman -S base-devel mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc`
5. Open "VS2013 x64 Native Tools Command Prompt" from the Start menu
6. Run `C:\msys64\mingw64_shell.bat` inside that

And then `cppbuild.sh install` and `mvn install` as usual. I've only tested it in 64 bits for now, but MSYS2 is working pretty well. Thanks @maximumspatium for introducing us to that!

**Comment by maalam** [comment]
Hi Samuel,

I am still facing the same issue that "[Warning] The POM for org.bytedeco:javacpp:jar:1.1-SNAPSHOT is missing, no dependency information available."

You have suggest me in my previous mail that "build and install the latest version of the javacpp module first. That will fix this error."

But, can you please help me, from where I get the latest version of javacpp module.

Please help me to build this.

Thanks and regards,
Manzoor Alam

**Comment by saudet** [comment]
@maalam Here: https://github.com/bytedeco/javacpp

**Comment by maximumspatium** [comment]
> But, can you please help me, from where I get the latest version of javacpp module.

You need to clone Javacpp's remote repository Samuel just pointed to, build and install it in your local Maven repository like that:
```
% git clone https://github.com/bytedeco/javacpp
% cd javacpp
% mvn install
```

That is what I meant in my Wiki guide with this
**Please note that you'll first need to compile and install the parent project - Javacpp.**
Recently, I even added the proper link to that Wiki page.

Happy building!

**Comment by maalam** [comment]
Hi Samuel,

I have downloaded the javacpp from https://github.com/bytedeco/javacpp and also clone this on to my machine. When I trying to run "mvn install" command it through an error:

Results :

Tests in error:
  org.bytedeco.javacpp.AdapterTest: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified
  org.bytedeco.javacpp.IndexerTest: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

And I also tried by removing the test folder of it.

Please help me to build this successfully.

Thanks and regards,
Manzoor Alam

**Comment by maximumspatium** [comment]
Hello,

your build fails in the test phase because Javacpp cannot find "cl" - C/C++ compiler coming with Microsoft Visual Studio.

You can either install M$ Visual Studio or skip Maven tests using the following invocation:

mvn -Dmaven.test.skip=true install

I hope that helps
Best regards
Max

**Comment by maalam** [comment]
Thanks for your reply dear,

I follow the steps and run the command : 

% mvn -Dmaven.test.skip=true install

Its javacpp build successfully.

Now I have to build javacpp-presets, As per Samuel suggestion and the documentation also that "You'll need to compile and install the parent project - Javacpp - first."
I did this. "Note: https://github.com/bytedeco/javacpp-presets/issues/44"

Now the javacpp and javacpp-presets is two different folder, what steps I have to follow to build javacpp-presets. or how I merge them?

Please help me to build javacpp-presets now

**Comment by maalam** [comment]
Hi Samuel,

This is an error which I am getting:

$ mvn install --projects .,leptonica,tesseract
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:opencv:jar:3.0.0-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:opencv:3.0.0-${project.parent.version}, E:\manzoor\javacpp-presets\opencv\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:ffmpeg:jar:2.8-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:ffmpeg:2.8-${project.parent.version}, E:\manzoor\javacpp-presets\ffmpeg\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:flycapture:jar:2.7.3.19-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:flycapture:2.7.3.19-${project.parent.version}, E:\manzoor\javacpp-presets\flycapture\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:libdc1394:jar:2.2.3-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:libdc1394:2.2.3-${project.parent.version}, E:\manzoor\javacpp-presets\libdc1394\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:libfreenect:jar:0.5.2-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:libfreenect:0.5.2-${project.parent.version}, E:\manzoor\javacpp-presets\libfreenect\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:videoinput:0.200-${project.parent.version}, E:\manzoor\javacpp-presets\videoinput\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:artoolkitplus:jar:2.3.1-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:artoolkitplus:2.3.1-${project.parent.version}, E:\manzoor\javacpp-presets\artoolkitplus\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:chilitags:jar:master-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:chilitags:master-${project.parent.version}, E:\manzoor\javacpp-presets\chilitags\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:flandmark:jar:1.07-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:flandmark:1.07-${project.parent.version}, E:\manzoor\javacpp-presets\flandmark\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:fftw:jar:3.3.4-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:fftw:3.3.4-${project.parent.version}, E:\manzoor\javacpp-presets\fftw\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:llvm:jar:3.7.0-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:llvm:3.7.0-${project.parent.version}, E:\manzoor\javacpp-presets\llvm\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:leptonica:jar:1.72-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:leptonica:1.72-${project.parent.version}, E:\manzoor\javacpp-presets\leptonica\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:tesseract:jar:3.04-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:tesseract:3.04-${project.parent.version}, E:\manzoor\javacpp-presets\tesseract\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:caffe:jar:master-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:caffe:master-${project.parent.version}, E:\manzoor\javacpp-presets\caffe\pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:cuda:jar:7.5-1.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:cuda:7.5-${project.parent.version}, E:\manzoor\javacpp-presets\cuda\pom.xml, line 14, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Inspecting build with total of 3 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 3 modules.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] JavaCPP Presets
[INFO] JavaCPP Presets for Leptonica
[INFO] JavaCPP Presets for Tesseract
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP Presets 1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-javadoc-plugin:2.9:jar (attach-javadocs) @ javacpp-presets ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO]
[INFO] --- maven-install-plugin:2.3:install (default-install) @ javacpp-presets ---
[INFO] Installing E:\manzoor\javacpp-presets\pom.xml to D:\Documents and Settings\Manzoor\.m2\repository\org\bytedeco\javacpp-presets\1.1-SNAPSHOT\javacpp-presets-1.1-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP Presets for Leptonica 1.72-1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.4:resources (generate-sources) @ leptonica ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\manzoor\javacpp-presets\leptonica\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3:compile (generate-sources) @ leptonica ---
[INFO] Compiling 1 source file to E:\manzoor\javacpp-presets\leptonica\target\classes
[INFO]
[INFO] --- javacpp:1.1-SNAPSHOT:build (generate-sources) @ leptonica ---
[INFO] Executing JavaCPP Builder
[INFO] Targeting E:\manzoor\javacpp-presets\leptonica\src\main\java\org\bytedeco\javacpp\lept.java
[ERROR] Failed to execute JavaCPP Builder: Could not parse "leptonica\alltypes.h": File does not exist
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JavaCPP Presets .................................... SUCCESS [  1.047 s]
[INFO] JavaCPP Presets for Leptonica ...................... FAILURE [  1.141 s]
[INFO] JavaCPP Presets for Tesseract ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.281 s
[INFO] Finished at: 2015-09-30T11:10:52+05:30
[INFO] Final Memory: 22M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.1-SNAPSHOT:build (generate-sources) on project leptonica: Failed to execute JavaCPP Builder: Could not parse "leptonica\alltypes.h": File does not exist -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :leptonica

Manzoor@admin MINGW64 /e/manzoor/javacpp-presets

**Comment by maximumspatium** [comment]
Could you try to clean up your build first?

```% mvn clean --projects .,leptonica,tesseract```

Then try to build your presets again. If this doesn't work, try to get Maven debug output using -X option, that is:

```% mvn install -X --projects .,leptonica,tesseract```

**Because the resulted output could be very large, please don't paste the whole log here. Please cut and paste only error-related lines.**

> Now the javacpp and javacpp-presets is two different folder, what steps I have to follow to build javacpp-presets. or how I merge them?

You don't need to do anything. Maven install automatically places all required artifacts in a hidden local folder on your machine so everything will just work.

You may want to check Maven's good documentation, especially its [Getting Started Guide](https://maven.apache.org/guides/getting-started/) in order to clarify questions related to Maven usage.

**Comment by maalam** [comment]
Hi Max, 
Thanks for your reply.

Max, can you please clear the compilation process of javacpp? because in the documentation there is an instruction like: 

"Compilation of Javacpp-presets
Please note that you'll first need to compile and install the parent project - Javacpp."

As per your instruction
I already build the "javacpp" in a separate folder, and trying to build the javacpp-presets in a separate folder by cleaning it up:
% cd javacpp-presets
% mvn clean --projects .,leptonica,tesseract

then, I run the:
bash cppbuild.sh -platform windows-x86_64 install leptonica tesseract

and then:
% mvn install --projects .,leptonica,tesseract

it is throwing an error.

I again run the:
% mvn install -X --projects .,leptonica,tesseract

and finally:
[INFO] Targeting E:\manzoor\javacpp-presets\leptonica\src\main\java\org\bytedeco        \javacpp\lept.java
[ERROR] Failed to execute JavaCPP Builder: Could not parse "leptonica\alltypes.h        ": File does not exist
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JavaCPP Presets .................................... SUCCESS [  1.016 s]
[INFO] JavaCPP Presets for Leptonica ...................... FAILURE [  1.062 s]
[INFO] JavaCPP Presets for Tesseract ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.094 s
[INFO] Finished at: 2015-09-30T15:53:47+05:30
[INFO] Final Memory: 22M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.1-SNAPSHOT:build (generate        -sources) on project leptonica: Failed to execute JavaCPP Builder: Could not par        se "leptonica\alltypes.h": File does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o        rg.bytedeco:javacpp:1.1-SNAPSHOT:build (generate-sources) on project leptonica:         Failed to execute JavaCPP Builder

what should I do?

thanks

**Comment by maximumspatium** [comment]
Let's see if we can solve your problem.

Which Windows are you running on? Which architecture (x86/x64)?

Please look into E:\manzoor\javacpp-presets\leptonica\cppbuild\windows-x86_64\include\leptonica\
Does this folder exist? Is alltypes.h there?

**Comment by maalam** [comment]
I am using Windows XP 64 bit. 

No only E:\manzoor\javacpp-presets\leptonica\cppbuild\windows-x86_64\ folder exist. and inside "windows-x86_64" there are folders as follow:
giflib-5.1.1
leptonica-1.72
libjpeg-turbo-1.4.1
libpng-1.6.17
libwebp-0.4.3
tiff-4.0.4 and
zlib-1.2.8

**Comment by maximumspatium** [comment]
> No only E:\manzoor\javacpp-presets\leptonica\cppbuild\windows-x86_64\ folder exist.

Yep, this clarifies the issue! ```bash cppbuild.sh -platform windows-x86_64 install leptonica tesseract```didn't run correctly! Have you checked for cppbuild.sh errors?

Please proceed as follows:
% cd E:\manzoor\javacpp-presets\
% bash cppbuild.sh -platform windows-x86_64 clean leptonica tesseract
% bash cppbuild.sh -platform windows-x86_64 install leptonica tesseract

Check the terminal output for errors. You shouldn't get any! Then check if you have alltypes.h in the above mentioned path.

Please ensure also that you're running these commands from MSYS2 prompt, not from Windows command prompt. This is a common mistake leading to subtle errors!

**Comment by maalam** [comment]
Hi Max,

I am running this on MSYS2 prompt and I run above commands but not created the "alltypes.h" file and folders.

**Comment by maximumspatium** [comment]
Do you get any errors? Could you send me your cppbuild.sh terminal output to maximumspatium at googlemail dot com?

**Comment by maalam** [comment]
Hi Max,

I am getting:
leptonica-1.72/version-notes.html
gcc  -O3 -Wall -c -o adler32.o adler32.c
[main] D:\cygnus\cygwin-b20\H-i586-cygwin32\bin\make.exe 1000 (0) sync_with_child: child 1196(0x32C) died before initialization with status code 0x80
[main] make 1000 (0) sync_with_child: *** child state waiting for longjmp
make.exe: vfork: No more processes

**Comment by maximumspatium** [comment]
It looks like you're experiencing an issue with CYGWIN and MSYS2. Googling for this issue reveals the following answer:

```You have to update latest version of msys-1.0.dll. (version 1.11 or later)```

Is it possible you have an older MSYS/CYGWIN somewhere in your machine?

I do use neither Windows nor Cygwin. Therefore I am not able to help you any further. I suggest to remove Cygwin, reinstall the MSYS2 + MINGW tool chain as described in the recent [Wiki documentation](https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows) and try again.

Please report afterwards whether you were able to solve the issue. Thanks.

**Comment by saudet** [comment]
Yeah, Cygwin doesn't support Java anyway. Please use MSYS2 only.

**Comment by iyusuf** [comment]
Hi,

I'm trying to build javacpp on a Windows 7 64bit. I can compile fine using 

> mvn clean install -Dmaven.test.skip=true 

But when I try to build running test I get Unsatisfied link error. It is saying that it can not load a 32 bit library. Here is my error out from surefire test report.
Tests in error:
  org.bytedeco.javacpp.AdapterTest: no jniAdapterTest in java.library.path
  org.bytedeco.javacpp.IndexerTest: no jniIndexerTest in java.library.path


<?xml version="1.0" encoding="UTF-8" ?>
<testsuite failures="0" time="4.221" errors="1" skipped="0" tests="1" name="org.bytedeco.javacpp.AdapterTest">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="c:\jdks\jdk1.7.0_79\jre\bin"/>
    <property name="java.vm.version" value="24.79-b02"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="C:\projects\my\javacpp\javacpp"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="Service Pack 1"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="C:\projects\my\javacpp\javacpp"/>
    <property name="java.runtime.version" value="1.7.0_79-b15"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="c:\jdks\jdk1.7.0_79\jre\lib\endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\iyusuf\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 7"/>
    <property name="classworlds.conf" value="c:\apps\apache-maven-3.3.1\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="c:\jdks\jdk1.7.0_79\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\CollabNet\Subversion Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinSCP\;C:\apps\Vagrant\bin;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\servers\jboss-eap-6.1\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\iyusuf\.dnx\bin;C:\Users\iyusuf\AppData\Roaming\npm;c:\jdks\jdk1.7.0_79\bin;c:\apps\apache-maven-3.3.1\bin;c:\msys64\usr\bin;c:\mingw64\mingw64\bin;."/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="51.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="6.1"/>
    <property name="user.home" value="C:\Users\iyusuf"/>
    <property name="user.timezone" value="America/Chicago"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.7"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="user.name" value="iyusuf"/>
    <property name="java.class.path" value="c:\apps\apache-maven-3.3.1\boot\plexus-classworlds-2.5.2.jar"/>
    <property name="org.slf4j.simpleLogger.defaultLogLevel" value="debug"/>
    <property name="java.vm.specification.version" value="1.7"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="c:\jdks\jdk1.7.0_79\jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean install -X"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.7.0_79"/>
    <property name="java.ext.dirs" value="c:\jdks\jdk1.7.0_79\jre\lib\ext;C:\Windows\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="c:\jdks\jdk1.7.0_79\jre\lib\resources.jar;c:\jdks\jdk1.7.0_79\jre\lib\rt.jar;c:\jdks\jdk1.7.0_79\jre\lib\sunrsasign.jar;c:\jdks\jdk1.7.0_79\jre\lib\jsse.jar;c:\jdks\jdk1.7.0_79\jre\lib\jce.jar;c:\jdks\jdk1.7.0_79\jre\lib\charsets.jar;c:\jdks\jdk1.7.0_79\jre\lib\jfr.jar;c:\jdks\jdk1.7.0_79\jre\classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="c:\apps\apache-maven-3.3.1"/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase time="4.221" classname="org.bytedeco.javacpp.AdapterTest" name="org.bytedeco.javacpp.AdapterTest">
    <error message="no jniAdapterTest in java.library.path" type="java.lang.UnsatisfiedLinkError">java.lang.UnsatisfiedLinkError: no jniAdapterTest in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:612)
	at org.bytedeco.javacpp.Loader.load(Loader.java:453)
	at org.bytedeco.javacpp.AdapterTest.setUpClass(AdapterTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsatisfiedLinkError: C:\projects\my\javacpp\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniAdapterTest.dll: Can&apos;t load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:595)
	... 23 more
</error>
    <system-out>Generating C:\projects\my\javacpp\javacpp\target\test-classes\org\bytedeco\javacpp\jniAdapterTest.cpp
Compiling C:\projects\my\javacpp\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniAdapterTest.dll
cl /IC:\jdks\jdk1.7.0_79\include /IC:\jdks\jdk1.7.0_79\include\win32 C:\projects\my\javacpp\javacpp\target\test-classes\org\bytedeco\javacpp\jniAdapterTest.cpp /W3 /Oi /O2 /EHsc /Gy /GL /MD /LD /link /OUT:C:\projects\my\javacpp\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniAdapterTest.dll 
</system-out>
    <system-err>Warning: Could not get the property named &quot;platform.compiler.cpp11&quot;
</system-err>
  </testcase>
</testsuite>

**Comment by saudet** [comment]
@iyusuf It looks like your using a 32-bit compiler. Try again with a 64-bit (x64) one.

**Comment by iyusuf** [comment]
@saudet 
I'm using JDK 64 bit. Do you mean I might be using a 32bit c++ compiler?

**Comment by saudet** [comment]
@iyusuf Yes, of course.

**Comment by arunartzoom** [comment]
HI ,

I am trying to run the LegacyLibrary exapmpe of javacpp

I am getting the following error . Can somebody please help 

`
D:\LAB\javacpp_test>java -cp javacpp.jar LegacyLibrary
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniLegacyLibrary in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
        at org.bytedeco.javacpp.Loader.load(Loader.java:438)
        at org.bytedeco.javacpp.Loader.load(Loader.java:381)
        at LegacyLibrary$LegacyClass.<clinit>(LegacyLibrary.java:8)
        at LegacyLibrary.main(LegacyLibrary.java:22)

D:\LAB\javacpp_test>`

**Comment by saudet** [comment]
@arunartzoom Try this here instead: https://github.com/bytedeco/javacpp#accessing-native-apis
